apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.dashboardsConfigMaps.glances }}
  labels:
{{ include "glances-k8s-stack.labels" . | indent 4 }}
data:
{{ (.Files.Glob "glances-dashboard/glances.grafana.json").AsConfig | indent 2 }}