
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ toYaml .Values.influxdb2.persistence.storageClass }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
