{
 "title": "Glances",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "from(bucket: \"grafana\")\r\n  |> range(start: -5m )\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hostname\")\r\n  |> map(fn: (r) => ({ _value: r.hostname }))\r\n  |> distinct()"
   },
   {
    "name": "container",
    "query": "from(bucket: \"grafana\")\r\n    |> range(start: -5m )\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"names\")\r\n  |> map(fn: (r) => ({ _value: r._value }))\r\n    |> distinct()"
   },
   {
    "name": "interface",
    "query": "from(bucket: \"grafana\")\r\n    |> range(start: -5m )\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\" and r[\"_field\"] == \"rx\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> map(fn: (r) => ({ _value: r.interface_name }))\r\n  |> distinct()"
   },
   {
    "name": "disk",
    "query": "from(bucket: \"grafana\")\r\n  |> range(start: -5m )\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\" and r[\"_field\"] == \"key\" and r[\"hostname\"] == \"${host}\" and r.disk_name !~ /loop/ )\r\n  |> map(fn: (r) => ({ _value: r.disk_name }))\r\n  |> distinct()"
   }
  ]
 },
 "panels": [
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "cpucore",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "localhost.load",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpucore\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "cpucore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1min",
     "column": "min1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.load",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min1\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "min1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load",
     "target": "randomWalk('random walk')"
    },
    {
     "alias": "5mins",
     "column": "min5",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.load",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min5\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "min5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    },
    {
     "alias": "15mins",
     "column": "min15",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.load",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min15\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "min15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "localhost.processcount",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processcount\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "series": "processcount"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "User",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"user\" or r[\"_field\"] == \"system\" or r[\"_field\"] == \"iowait\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "localhost.mem",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem"
    },
    {
     "alias": "Max",
     "column": "total",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "localhost.mem",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem"
    }
   ]
  },
  {
   "title": "$interface network interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "In",
     "column": "enp0s25.rx",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "localhost.network",
     "query": "// SELECT mean(\"$interface.rx\")/mean(\"$interface.time_since_update\")*8 FROM \"localhost.network\" WHERE $timeFilter GROUP BY time($interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx\" or r[\"_field\"] == \"time_since_update\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"${interface}\")\r\n   |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      \"Download\": ( r.rx / r.time_since_update ) * 8.0\r\n  }))\r\n    \r\n \r\n\r\n",
     "select": [
      [
       { "params": [ "eth0.rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    },
    {
     "alias": "Out",
     "column": "eth0.tx*-1",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "localhost.network",
     "query": "//SELECT mean(\"$interface.tx\")/mean(\"$interface.time_since_update\")*8*-1 FROM \"localhost.network\" WHERE $timeFilter GROUP BY time($interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx\" or r[\"_field\"] == \"time_since_update\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"interface_name\"] == \"${interface}\")\r\n   |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  \r\n  //|> map(fn: (r) => ({ r with _value: ( r.rx / r.time_since_update ) * 8.0 }))\r\n  // |> group()\r\n\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      \"Upload\": ( r.tx / r.time_since_update ) * 8.0\r\n  }))\r\n",
     "select": [
      [
       { "params": [ "eth0.tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "localhost.memswap",
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\" )\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memswap\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    },
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memswap\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "$disk disk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Read",
     "column": "sda2.read_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.diskio",
     "query": "// SELECT mean(\"$disk.read_bytes\") FROM \"localhost.diskio\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"$disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "sda2.read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    },
    {
     "alias": "Write",
     "column": "sda2.write_bytes",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.diskio",
     "query": "//SELECT mean(\"$disk.write_bytes\") FROM \"localhost.diskio\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"disk_name\"] == \"$disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "sda2.write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    }
   ]
  },
  {
   "title": "/ Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "column": "\"/.used\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.fs",
     "query": "// SELECT mean(\"/.used\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval) fill(null)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"mnt_point\"] == \"/\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "/.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    },
    {
     "alias": "Max",
     "column": "\"/.size\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.fs",
     "query": "// SELECT mean(\"/.size\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval) fill(null)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"size\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"mnt_point\"] == \"/\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "/.size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  {
   "title": "/ used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "\"/.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "localhost.fs",
     "query": "// SELECT mean(\"/.percent\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"mnt_point\"] == \"/\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "/.percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  {
   "title": "/boot used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "column": "\"/home.percent\"",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "localhost.fs",
     "query": "// SELECT mean(\"/boot/efi.percent\") FROM \"localhost.fs\" WHERE $timeFilter GROUP BY time($interval)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"mnt_point\"] == \"/boot\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "/boot.percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  { "title": "Containers", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$container container CPU consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.docker",
     "query": "// SELECT mean(\"$container.cpu_percent\") FROM \"localhost.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${container}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "// SELECT mean(\"$container.memory_usage\") FROM \"localhost.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${container}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$container container CPU consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.docker",
     "query": "// SELECT mean(\"$container.cpu_percent\") FROM \"localhost.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${container}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "// SELECT mean(\"$container.memory_usage\") FROM \"localhost.docker\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${container}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU details", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "user",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT mean(\"user\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"user\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "user",
     "function": "min",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT min(\"user\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"user\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> yield(name: \"min\")",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "user",
     "function": "max",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT max(\"user\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"user\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU system",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "system",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT mean(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "system",
     "function": "min",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT min(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> yield(name: \"min\")",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "system",
     "function": "max",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT max(\"system\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT mean(\"iowait\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iowait\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "min",
     "column": "iowait",
     "function": "min",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT min(\"iowait\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iowait\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n  |> yield(name: \"min\")",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "max",
     "column": "iowait",
     "function": "max",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT max(\"iowait\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"iowait\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT mean(\"ctx_switches\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ctx_switches\" or r[\"_field\"] == \"time_since_update\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      \"ctx_switches\": r.ctx_switches/r.time_since_update\r\n  }))",
     "select": [
      [
       { "params": [ "time_since_update" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mean",
     "column": "iowait",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "localhost.cpu",
     "query": "// SELECT mean(\"interrupts\") / mean(\"time_since_update\") FROM \"localhost.cpu\" WHERE $timeFilter GROUP BY time($interval)\r\nfrom(bucket: \"grafana\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"interrupts\" or r[\"_field\"] == \"time_since_update\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      \"interrupts\": r.interrupts/r.time_since_update\r\n  }))",
     "select": [
      [
       { "params": [ "time_since_update" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  { "title": "Sensors", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Ambiant temperature",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "AmbientTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "localhost.sensors",
     "select": [
      [
       { "params": [ "Ambient.value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cpu Temperature",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "alias": "CpuTemperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "localhost.sensors",
     "select": [
      [
       { "params": [ "CPU.value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}